### ISSUE TITLE
Can no longer build netstandard2.0 library project that uses DynamoDB attributes after upgrading from dotnet core sdk 2.1.302 to 2.1.400.

### ISSUE THREAD

**Issue by smsenesac** [aws/aws-sdk-net#1045]
## Expected Behavior

- netstandard2.0 library project using DynamoDB attributes would build successfully with dotnet core sdk 2.1.302
- it should continue to build successfully with dotnet core sdk 2.1.400

## Current Behavior
netstandard2.0 library project using DynamoDB attributes no longer builds after upgrading to dotnet core sdk 2.1.400

> error CS0012: The type ‘Attribute’ is defined in an assembly that is not referenced. You must add a reference to assembly ‘System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a’.

## Possible Solution
- modifying library project to target netcoreapp2.1 instead of netstandard2.0 fixes the build.
- not ideal solution, though, as it limits the runtime flexibility of the library.

## Steps to Reproduce (for bugs)
The offending code:
```
using System;
using Amazon.DynamoDBv2.DataModel;

namespace Foo.Data.Profiles.Models
{
    [DynamoDBTable("Profiles")]
    public class Profile
    {
        [DynamoDBHashKey]
        public string UserId { get; set; }
    }
}
```

The .csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NeutralLanguage>en-US</NeutralLanguage>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageVersion>0.1.0.0</PackageVersion>
    <PackageId>Foo.Data.Profiles</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.13.0" />
  </ItemGroup>

</Project>
```

The build script:
```
#!/bin/bash

set -e

cd src/Foo

dotnet build -c Release
```

## Context
would like to make this work for a netstandard2.0 project

## Your Environment

* AWSSDK.Core version used: AWSSDK.DynamoDBv2 3.3.13.0
* Operating System and version: macOS 10.13.6
* Visual Studio version: N/A
* Targeted .NET platform: standard 2.0

## .NET Core Info

* .NET Core version used for development: 2.1.400
* .NET Core version installed in the environment where application runs: N/A
* Output of `dotnet --info`: 
> .NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

> Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.400/

> Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

> .NET Core SDKs installed:
  2.0.3 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.400 [/usr/local/share/dotnet/sdk]

> .NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by klaytaybai** [comment]
Hi @smsenesac, I wasn't able to reproduce this issue despite the great reproduction info you provided in this issue and the similar one you made in the [dotnet/standard repo](https://github.com/dotnet/standard/issues/855).  I would suggest checking your assemblies in your dependencies and verifying that you have a version of System.Runtime greater than or equal to 4.0.20.0.  Creating the project from scratch using the information you provided, I had references to System.Runtime version 4.1.0 as dependencies of AWSSDK.DynamoDBv2.  You may want to try updating your dependencies.

I will check with some other team members, but at this time, I don't think this is an issue related to our SDK.  I am going to label this issue as closing soon until I hear anything else from you or somebody from our SDK team that would lead me to believe otherwise.  Meanwhile, please let us know if you find a solution that doesn't require you to target netcoreapp2.1 instead of netstandard2.0.

**Comment by smsenesac** [comment]
Thanks for looking into this!  I've narrowed this down to an internal private nuget package.  It's definitely nothing in the SDK or the AWS library.
