### ISSUE TITLE
Build of a project referencing AWSSDK.S3 fails with Error CS8032 after an update

### ISSUE THREAD

**Issue by PeterBenko** [aws/aws-sdk-net#2990]
### Describe the bug

After updating AWSSDK.S3 from 3.7.107 to 3.7.107.1 the build suddenly fails.

### Expected Behavior

The build should still work after the update.

### Current Behavior

After updating AWSSDK.S3 from 3.7.107 to 3.7.107.1 the build suddenly fails with the following error message:

    CSC : error CS8032: An instance of analyzer Amazon.S3.CodeAnalysis.PropertyValueAssignmentAnalyzer cannot be created from C:\Users\peter.benko\.nuget\packages\awssdk.s3\3.7.107.1\analyzers\dotnet\cs\AWSSDK.S3.CodeAnalysis.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
Upon reverting to 3.7.107 the build works again. 
The project in question is `net48` class library, built for `x86`.

### Reproduction Steps

[Minimal repro solution](https://github.com/PeterBenko/aws-sdk-net-issues-2990) -> all is fine if you downgrade to 3.7.107

### Additional Information/Context

- Surprisingly, this issues is present only when using 32bit SDK since the build works on CI with 64but SDK
- Possibly caused by same root cause as https://github.com/aws/aws-sdk-net/issues/2989

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.107.1

### Targeted .NET Platform

.NET Framework 4.8

### Operating System and version

Windows 10

**Comment by dscpinheiro** [comment]
Thanks for reporting @PeterBenko, it's the same problem as the other issue.
I'll close this one and continue the investigation / resolution there.

**Comment by dscpinheiro** [comment]
@PeterBenko I wanted to ask a follow-up question to this issue: What version of Visual Studio were you using for that reproduction repository (https://github.com/PeterBenko/aws-sdk-net-issues-2990)?

**Comment by PeterBenko** [comment]
The IDE I used was Rider.

If you’re asking because of the .csproj structure - I’ve manually clobbered it together to mimic the project that was giving us troubles.

**Comment by dscpinheiro** [comment]
Got it, thanks for the answer. We're thinking about changing the analyzer to target `netstandard` again, but will probably use a lower version of the `Microsoft.CodeAnalysis` package (as recommended on the other issue).

I haven't tested with Rider, will take a look.
